### ISSUE TITLE
Dashboard not functioning properly - errors with dashboard.wsgi

### ISSUE THREAD

**Issue by tstilwel** [joefutrelle/ifcb-dashboard#40]
This error appears every time I try loading the dashboard.  

[Wed May 20 06:18:15.509757 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964] mod_wsgi (pid=66): **Exception occurred processing WSGI script '/vagrant/dashboard.wsgi**'.
[Wed May 20 06:18:15.509802 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964] Traceback (most recent call last):
[Wed May 20 06:18:15.509823 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
[Wed May 20 06:18:15.510232 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     return self.wsgi_app(environ, start_response)
[Wed May 20 06:18:15.510248 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
[Wed May 20 06:18:15.510268 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     response = self.make_response(self.handle_exception(e))
[Wed May 20 06:18:15.510278 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
[Wed May 20 06:18:15.510291 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     reraise(exc_type, exc_value, tb)
[Wed May 20 06:18:15.510298 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Wed May 20 06:18:15.510309 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     response = self.full_dispatch_request()
[Wed May 20 06:18:15.510316 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed May 20 06:18:15.510326 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     rv = self.handle_user_exception(e)
[Wed May 20 06:18:15.510332 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Wed May 20 06:18:15.510342 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     reraise(exc_type, exc_value, tb)
[Wed May 20 06:18:15.510348 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed May 20 06:18:15.510358 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     rv = self.dispatch_request()
[Wed May 20 06:18:15.510364 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed May 20 06:18:15.510388 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed May 20 06:18:15.510399 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]   File "/vagrant/oii/ifcb2/dashboard/app.py", line 537, in nearest
[Wed May 20 06:18:15.510734 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964]     resp = canonicalize_bin(bin)
[Wed May 20 06:18:15.510754 2020] [wsgi:error] [pid 66:tid 139854026680064] [remote 172.17.0.1:37964] **UnboundLocalError: local variable 'bin' referenced before assignment**

If I click on Metrics or other links next to View, I receive an Internal Server Error message with a similar error message in error.logs

local variable 'b' referenced before assignment

**Comment by tstilwel** [comment]
Actually this doesn't seem to be a problem. Closing
